"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { title } from "process";
import { useEffect, useState } from "react";
import axios from "axios";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [user, setUser] = useState(null);
  useEffect(() => {
    const getUser = async () => {
      const response = await axios.get(
        `http://localhost:3001/user/6800b35d039f8894d38c7516`
      );

      setUser(response.data.oneUser);
    };
    getUser();
  }, []);
  console.log(user);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-center"
          theme="dark"
          className=" z-10 text-white w-full h-13 rounded-md bg-black"
          toastOptions={{
            className: "bg-black text-white",
          }}
        />
        {children}
      </body>
    </html>
  );
}
// {
//   toast: "bg-black text-white border ",
//   title: "text-white",
//   description: "text-gray-300",
//   actionButton: "bg-white text-black",
//   cancelButton: "text-white",
//   closeButton: "text-white",
// }
